In [2]:
import numpy as np

# Defining two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Sum of matrices
sum_matrix = A + B

# Difference of matrices
diff_matrix = A - B

# Transpose of matrices
transpose_A = A.T
transpose_B = B.T

# Product of matrices (Matrix Multiplication)
product_matrix = np.dot(A, B)

# Displaying the results
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nSum of A and B:\n", sum_matrix)
print("\nDifference of A and B:\n", diff_matrix)
print("\nTranspose of A:\n", transpose_A)
print("\nTranspose of B:\n", transpose_B)
print("\nProduct of A and B:\n", product_matrix)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Difference of A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of B:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]

Product of A and B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
